### ISSUE TITLE
Installation with pip failed

### ISSUE THREAD

**Issue by nadegeguiglielmoni** [cmdoret/tinycov#3]
Hello, 

When trying to install tinycov using pip, I encountered the following error:

`
Traceback (most recent call last):
  File "/dss/dssfs02/lwp-dss-0001/pn69xe/pn69xe-dss-0000/di52zuy/ignite_tools_py3/bin/pip", line 7, in <module>
    from pip._internal.main import main
ModuleNotFoundError: No module named 'pip._internal.main'
`

I managed to install it however by running `python setup.py install --user`.

**Comment by cmdoret** [comment]
Hi, 

It seems to be a pip-related bug linked to version mismatch: https://github.com/pypa/pip/issues/5373

Apparently this bug can appear when you update the distribution's pip using `sudo pip install -U pip`. if that's what happened, reinstalling the distribution's pip seems to work: https://github.com/pypa/pip/issues/5253

**Comment by nadegeguiglielmoni** [comment]
Thanks for your help. In my case I cannot do that because I am using a cluster, but the most important is that it's working somehow.
